ansible_ssh_pass: YourPaSsWoRd
ansible_become_pass: YourPaSsWoRd
sonicadmin_user: admin
sonicadmin_password: YourPaSsWoRd
sonicadmin_initial_password: YourPaSsWoRd

console_login:
  console_telnet: 
    user: "root"
    passwd: ["password1", "password2"]
  console_ssh: 
    user: "root"
    passwd: ["password1", "password2"]
  console_ssh_menu_ports:
    user: "root"
    passwd: ["password1", "password2"]
