---

- conf-name: ptf1-m
  group-name: ptf1
  topo: ptf32
  ptf_image_name: docker-ptf
  ptf: ptf-unknown
  ptf_ip: 10.255.0.188/24
  ptf_ipv6:
  server: server_1
  vm_base:
  dut:
    - str-msn2700-01
  inv_name: lab
  auto_recover: 'False'
  comment: Test ptf Mellanox

- conf-name: ptf2-b
  group-name: ptf2
  topo: ptf64
  ptf_image_name: docker-ptf
  ptf: ptf-unknown
  ptf_ip: 10.255.0.189/24
  ptf_ipv6:
  server: server_1
  vm_base:
  dut:
    - lab-s6100-01
  inv_name: lab
  auto_recover: 'False'
  comment: Test ptf Broadcom

- conf-name: vms-sn2700-t1
  group-name: vms1-1
  topo: t1
  ptf_image_name: docker-ptf
  ptf: ptf-unknown
  ptf_ip: 10.255.0.178/24
  ptf_ipv6:
  server: server_1
  vm_base: VM0100
  dut:
    - str-msn2700-01
  inv_name: lab
  auto_recover: 'True'
  comment: Tests Mellanox SN2700 vms

- conf-name: vms-sn2700-t1-lag
  group-name: vms1-1
  topo: t1-lag
  ptf_image_name: docker-ptf
  ptf: ptf-unknown
  ptf_ip: 10.255.0.178/24
  ptf_ipv6:
  server: server_1
  vm_base: VM0100
  dut:
    - str-msn2700-01
  inv_name: lab
  auto_recover: 'True'
  comment: Tests Mellanox SN2700 vms

- conf-name: vms-sn2700-t0
  group-name: vms1-1
  topo: t0
  ptf_image_name: docker-ptf
  ptf: ptf-unknown
  ptf_ip: 10.255.0.178/24
  ptf_ipv6:
  server: server_1
  vm_base: VM0100
  dut:
    - str-msn2700-01
  inv_name: lab
  auto_recover: 'True'
  comment: Tests Mellanox SN2700 vms

- conf-name: vms-s6000-t0
  group-name: vms2-1
  topo: t0
  ptf_image_name: docker-ptf
  ptf: ptf-unknown
  ptf_ip: 10.255.0.179/24
  ptf_ipv6:
  server: server_1
  vm_base: VM0100
  dut:
    - lab-s6000-01
  inv_name: lab
  auto_recover: 'True'
  comment: Tests Dell S6000 vms

- conf-name: vms-a7260-t0
  group-name: vms3-1
  topo: t0-116
  ptf_image_name: docker-ptf
  ptf: ptf-unknown
  ptf_ip: 10.255.0.180/24
  ptf_ipv6:
  server: server_1
  vm_base: VM0100
  dut:
    - lab-a7260-01
  inv_name: lab
  auto_recover: 'True'
  comment: Tests Arista A7260 vms

- conf-name: vms-s6100-t0
  group-name: vms4-1
  topo: t0-64
  ptf_image_name: docker-ptf
  ptf: ptf-unknown
  ptf_ip: 10.255.0.181/24
  ptf_ipv6:
  server: server_1
  vm_base: VM0100
  dut:
    - lab-s6100-01
  inv_name: lab
  auto_recover: 'True'
  comment: Tests Dell S6100 vms

- conf-name: vms-s6100-t1
  group-name: vms4-1
  topo: t1-64
  ptf_image_name: docker-ptf
  ptf: ptf-unknown
  ptf_ip: 10.255.0.182/24
  ptf_ipv6:
  server: server_1
  vm_base: VM0100
  dut:
    - lab-s6100-01
  inv_name: lab
  auto_recover: 'True'
  comment: Tests Dell S6100 vms

- conf-name: vms-s6100-t1-lag
  group-name: vms5-1
  topo: t1-64-lag
  ptf_image_name: docker-ptf
  ptf: ptf-unknown
  ptf_ip: 10.255.0.183/24
  ptf_ipv6:
  server: server_1
  vm_base: VM0100
  dut:
    - lab-s6100-01
  inv_name: lab
  auto_recover: 'True'
  comment: ests Dell S6100 vms

- conf-name: vms-multi-dut
  group-name: vms1-duts
  topo: ptf64
  ptf_image_name: docker-ptf
  ptf: ptf-unknown
  ptf_ip: 10.255.0.184/24
  ptf_ipv6:
  server: server_1
  vm_base: VM0100
  dut:
    - dut-host1
    - dut-host2
  inv_name: lab
  auto_recover: 'True'
  comment: Example Multi DUTs testbed

- conf-name: vms-example-ixia-1
  group-name: vms6-1
  topo: t0-64
  ptf_image_name: docker-ptf-ixia
  ptf: example-ixia-ptf-1
  ptf_ip: 10.0.0.30/32
  ptf_ipv6:
  server: server_6
  vm_base: VM0600
  dut:
    - example-s6100-dut-1
  inv_name: lab
  auto_recover: 'True'
  comment: superman

- conf-name: ixanvl-vs-conf
  group-name: anvl
  topo: ptf32
  ptf_image_name: docker-ptf-anvl
  ptf: ptf-unknown
  ptf_ip: 10.250.0.100/24
  ptf_ipv6:
  server: server_1
  vm_base:
  dut:
    - vlab-01
  inv_name: lab
  auto_recover: 'True'
  comment: Test ptf ANVL SONIC VM

- conf-name: 01-t0
  group-name: vms1-t0
  topo: t0
  ptf_image_name: docker-ptf
  ptf: ptf_vms1-t0
  ptf_ip: 10.250.128.196/16
  ptf_ipv6:
  server: server_1
  vm_base: VM0100
  dut:
    - dut_cls_dx010-01
  inv_name: lab
  auto_recover: 'False'
  comment: Hedgehog T0 topology VMAccel Testbed 01

- conf-name: 01-t1
  group-name: vms1-t0
  topo: t1
  ptf_image_name: docker-ptf
  ptf: ptf_vms1-t0
  ptf_ip: 10.250.128.196/16
  ptf_ipv6:
  server: server_1
  vm_base: VM0100
  dut:
    - dut_cls_dx010-01
  inv_name: lab
  auto_recover: 'False'
  comment: Hedgehog T1 topology VMAccel Testbed 01