# Please update the actual username and password according to your lab configuration

# do not need to set creds, se use static fanout config for sn2700.
# if we want to use dynamic, then update ansible/roles/fanout/tasks/fanout_eos.yml,
# and update corresponding fanout template
# and update creds in ansible/testbed-new.yaml
ansible_ssh_user: user
ansible_ssh_pass: password
fanout_mlnx_user: admin
fanout_mlnx_password: admin
fanout_sonic_user: admin
fanout_sonic_password: password

# Credential for accessing the network cli interface
fanout_network_user: netadmin
fanout_network_password: netpassword

# Credential for accessing the Linux shell
fanout_shell_user: shelladmin
fanout_shell_password: shellpassword
