---
# ansible_user: use_own_value
# ansible_password: use_own_value
# ansible_become_password: use_own_value
ansible_user: hedgehog
ansible_password: hedgehog
ansible_become_password: hedgehog

# Use the following username/password variables to login to vm hosts
# instead of the default variables (defined above).
vm_host_user: hedgehog
vm_host_password: hedgehog
vm_host_become_password: hedgehog
